#!/usr/bin/env bash
# firstboot-wizard.sh — Interactive first-boot setup wizard
# Generates a fresh config.yaml from user input (not sed/append on existing file).
set -euo pipefail

CONFIG="/opt/famclaw/config.yaml"

echo ""
echo "═══ FamClaw Setup Wizard ═══"
echo ""

# ── Parent ────────────────────────────────────────────────────────────────────

read -rp "Parent name (e.g., Mom): " PARENT_NAME
PARENT_NAME="${PARENT_NAME:-Parent}"

while true; do
    read -rsp "Parent PIN (4+ digits, required): " PARENT_PIN
    echo ""
    if [ ${#PARENT_PIN} -ge 4 ]; then
        break
    fi
    echo "  PIN must be at least 4 digits."
done

USERS_YAML="  - name: \"$(echo "$PARENT_NAME" | tr '[:upper:]' '[:lower:]')\"
    display_name: $(printf '%s' "$PARENT_NAME" | sed 's/"/\\"/g; s/:/\\:/g')
    role: \"parent\"
    pin: \"$PARENT_PIN\"
    color: \"#6366f1\""

# ── Children ──────────────────────────────────────────────────────────────────

while true; do
    echo ""
    read -rp "Add a child? (y/n): " ADD_CHILD
    [ "$ADD_CHILD" = "y" ] || [ "$ADD_CHILD" = "Y" ] || break

    read -rp "  Child's name: " CHILD_NAME
    [ -n "$CHILD_NAME" ] || continue

    echo "  Age group:"
    echo "    1) Under 8"
    echo "    2) 8-12"
    echo "    3) 13-17"
    read -rp "  Choose (1-3): " AGE_CHOICE

    case "$AGE_CHOICE" in
        1) AGE_GROUP="under_8" ;;
        2) AGE_GROUP="age_8_12" ;;
        3) AGE_GROUP="age_13_17" ;;
        *) AGE_GROUP="under_8" ;;
    esac

    USERS_YAML="$USERS_YAML
  - name: \"$(echo "$CHILD_NAME" | tr '[:upper:]' '[:lower:]')\"
    display_name: \"$CHILD_NAME\"
    role: \"child\"
    age_group: \"$AGE_GROUP\""
done

# ── Gateways ──────────────────────────────────────────────────────────────────

GW_YAML="gateways:
  telegram:
    enabled: false
  discord:
    enabled: false
  whatsapp:
    enabled: false"

echo ""
read -rp "Enable Telegram bot? (y/n): " TG
if [ "$TG" = "y" ] || [ "$TG" = "Y" ]; then
    read -rp "  Telegram bot token: " TG_TOKEN
    GW_YAML="gateways:
  telegram:
    enabled: true
    token: \"$TG_TOKEN\"
  discord:
    enabled: false
  whatsapp:
    enabled: false"
fi

read -rp "Enable Discord bot? (y/n): " DC
if [ "$DC" = "y" ] || [ "$DC" = "Y" ]; then
    read -rp "  Discord bot token: " DC_TOKEN
    GW_YAML=$(echo "$GW_YAML" | sed "s/discord:/discord:\n    enabled: true\n    token: \"$DC_TOKEN\"/; s/  discord:\n    enabled: false/  discord:\n    enabled: true\n    token: \"$DC_TOKEN\"/")
fi

# ── Write fresh config (not appending to existing) ───────────────────────────

# Read server secret from existing config (generated by firstboot.sh)
SECRET=$(grep 'secret:' "$CONFIG" 2>/dev/null | head -1 | awk '{print $2}' | tr -d '"' || echo "change-me")

cat > "$CONFIG" << YAML
server:
  host: "0.0.0.0"
  port: 8080
  secret: "$SECRET"
  mdns_name: "famclaw"

llm:
  base_url: ""
  model: ""

users:
$USERS_YAML

$GW_YAML

storage:
  db_path: "./data/famclaw.db"
YAML

echo ""
echo "  Configuration saved to $CONFIG"
echo "  Configure your LLM endpoint via the web UI: http://famclaw.local:8080"
